# Generated by Django 3.2.8 on 2022-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_url_slug', models.TextField()),
                ('question_id', models.IntegerField()),
                ('difficulty', models.TextField()),
                ('content', models.TextField()),
                ('similar_questions', models.TextField()),
                ('topics', models.TextField()),
                ('videos', models.TextField()),
            ],
        ),
    ]
