# Generated by Django 3.2.8 on 2022-03-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Queries',
        ),
    ]
