# Generated by Django 3.2.8 on 2022-03-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_store_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='question_url_slug',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='similar_questions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='topics',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='videos',
            field=models.TextField(null=True),
        ),
    ]
